### ISSUE TITLE
Image updates in `openjdk:8` cause build failure

### ISSUE THREAD

**Issue by yosifkit** [docker-flink/docker-flink#17]
We updated the `openjdk:8` images to Debian Stretch in https://github.com/docker-library/openjdk/pull/124 so that it can follow the latest openjdk builds and have newer dependencies. As a result, `libsnappy1` is no longer available, but is now [`libsnappy1v5`](https://packages.debian.org/stretch/libsnappy1v5).

Do you want me to make a PR to update `Dockerfile-debian.template`?

**Comment by patricklucas** [comment]
Sorry for the late reply; I'm currently on vacation. Go ahead and make the PR, but I'd really like to test it with a simple Flink job that consumes snappy-compressed data in Kafka and likely won't have time for that for a few weeks.

**Comment by iemejia** [comment]
@patricklucas if you can point me to the test you use I can test it for you and confirm that the fix works.
