### ISSUE TITLE
Add a new image based on openjdk:8-jre-slim

### ISSUE THREAD

**Issue by iemejia** [docker-flink/docker-flink#19]
There is a new set of images (still experimental) that are slimmer versions of the debian and openjdk image, this can reduce the size of our current flink image.

**Comment by guenhter** [comment]
@iemejia Have you also thought about going directly to `openjdk:8-jre-alpine`? This is much smaller than the `slim` variant.

**Comment by iemejia** [comment]
Yes @guenhter we already had a version for alpine but there were some issues in the state persistence using rocksdb because alpine does not use libc, I already submitted a PR that seems to fix it, it should be reviewed and merge soon.
https://github.com/docker-flink/docker-flink/pull/22.

**Comment by iemejia** [comment]
Following the argument on #25 this probably should not replace the default but be a separate image.

**Comment by iemejia** [comment]
Not much demand for this so closing for now. If someone requests this we should open the issue in Apache Flink's issue tracker.
