### ISSUE TITLE
The docker-flink image should be built via automated builds

### ISSUE THREAD

**Issue by iemejia** [docker-flink/docker-flink#2]
The docker hub configuration shall not have manually pushed images, those should be built from this repo.
This guarantees assurance for its users that the images have not been altered.

Probably we shall move this into a new github organization (docker-flink) to make maintenance of the automated builds easier.

**Comment by iemejia** [comment]
Other god thing of having a github organization is that we can fork the docs repo from docker-library into the organization to co-share the  maintenance there too.

**Comment by patricklucas** [comment]
Yes, automated builds are a must. This GitHub repo is temporary while we develop the Dockerfiles and relevant scripts, then hopefully we can move this into docker-library. In the mean time, if you want to test builds, I recommend forking the repo, but we still have a good bit of work to do to get this in shape. (See comments on the [JIRA issue](https://issues.apache.org/jira/browse/FLINK-3026) and in [README.md](https://github.com/patricklucas/docker-flink/blob/f3674068d7163e6d890552ba7a418667938a875d/README.md))

**Comment by iemejia** [comment]
I agree there is still work to do, but we can iterate faster if you just create the docker-flink organization and move this repo there, you don't need to give me additional permisions I think and the move works flawlessly, I already did for another project.

**Comment by iemejia** [comment]
Can you do this ? Anyway as you said in the end things will end up in docker-library so I don't think this is an issue.

**Comment by patricklucas** [comment]
It's done.

**Comment by iemejia** [comment]
Thanks it seems you have to give me a little bit more of access so I can trigger the builds from hub.docker.com you should receive from an email from github requesting this soon I think.

**Comment by iemejia** [comment]
Great it is working now, however I won't close this issue until we fully map all the variants for the current release into the docker hub official images.

**Comment by patricklucas** [comment]
I think the "automated build" bit of Docker Hub is insufficient here, no? From what I can tell, it's really meant more for single Dockerfiles.

The process for official images appears a bit different. The `generate-stackbrew-library.sh` script creates the file that goes in the docker-library/official-images repo, then the images are built and tagged automatically from there.

I don't think that maps very well onto the "automated builds" features of Docker Hub, so until then, I'll just run the "bashbrew" tool from docker-library/official-images manually to build, tag, and push the images to my repo (plucas/flink).

**Comment by iemejia** [comment]
Closing because this is already done too.
