### ISSUE TITLE
Add tests to validate a new image release

### ISSUE THREAD

**Issue by iemejia** [docker-flink/docker-flink#21]
We lack tests to ensure that the modifications we do to the docker files don't break the images, we need to automate or at least document a simple validation test for this. A simple and valuable case is a simple flink job with checkpointing.

**Comment by patricklucas** [comment]
Do you think we could accomplish this some how using travis on this repo?

**Comment by iemejia** [comment]
That was exactly what I was thinking yesterday, I even found a post that tests docker images with travis and qemu for the arm case. But what do you imagine should be our basic core test case?
