### ISSUE TITLE
Doc issue ?

### ISSUE THREAD

**Issue by therw** [docker-flink/docker-flink#23]
Hello,

I believe that there might be a mistake in the doc in "Running a JobManager or a TaskManager"
Given command for jobmanager : "$ docker run --name flink_jobmanager -d -t flink taskmanager"
Given command for taskmanager : "$ docker run --name flink_taskmanager -d -t flink taskmanager"

For me jobmanager command should be "$ docker run --name flink_jobmanager -d -t flink jobmanager"

Am I right or did I understand something wrong ?

**Comment by patricklucas** [comment]
Nope, you're right. Thanks for the report, I'll get it fixed!
