### ISSUE TITLE
Support multiple architectures in the docker images

### ISSUE THREAD

**Issue by iemejia** [docker-flink/docker-flink#26]
Official docker images support now multi architecture builds, we need to add support for this in the docker image.
https://blog.docker.com/2017/09/docker-official-images-now-multi-platform/
It seems we need just to add some metadata and validate that this works.
https://github.com/docker-library/official-images#multiple-architectures

**Comment by iemejia** [comment]
For ref, you can validate the supported architectures of an image by running:
```
 docker run mplatform/mquery
```

**Comment by patricklucas** [comment]
I added ARM64v8 for #40, but in general the blocker for merging is testability, given I don't really have convenient access to e.g. ARM or PPC hardware.

**Comment by patricklucas** [comment]
This was superseded by #41. Closing.
