### ISSUE TITLE
Support Hadoop-free 1.4

### ISSUE THREAD

**Issue by patricklucas** [docker-flink/docker-flink#30]
The scripts currently don't support the absence of a Hadoop version, though Flink 1.4 now includes a Hadoop-free release.

Update the scripts to build a Hadoop-free image, and ideally, change the Hadoop-ful images to use it as an upstream, only adding the additional jar to `/opt/flink/lib`.

**Comment by clatko** [comment]
added hadoopless here - https://github.com/docker-flink/docker-flink/pull/38

**Comment by patricklucas** [comment]
There's a bit of trickiness actually introducing the hadoopless images due to how we've done tagging thus far: currently, omitting the "hadoopX" part of the tag implies the latest hadoop variant (currently 2.8), but omitting that part is also how the upstream release archives indicate hadooplessness.

I propose that we introduce the hadoop-free images with Flink 1.5 (due to be released soon), making them the default (i.e. when a hadoop version is not specified), at the same time dropping the 1.3 images.

**Comment by iemejia** [comment]
+1 @patricklucas It sounds easier to do at the moment of the switch to 1.5. And better not to change the expected labels of 1.4.

**Comment by patricklucas** [comment]
This is done, though I'm still not sure how to go about making the hadoop images downstream from the hadoop-less ones. I don't think this is a critical issue since it's mostly a disk space optimization.
