### ISSUE TITLE
Drop 'USER flink' and make docker-entrypoint.sh drop privs

### ISSUE THREAD

**Issue by patricklucas** [docker-flink/docker-flink#5]
We may want to teach `docker-entrypoint.sh` to drop privs to the flink user so `docker run flink bash` gives a root shell into the container. An example is Elasticsearch ([debian](https://github.com/docker-library/elasticsearch/blob/d1765774a1effc5436f3d1f4ad6826dd9ed2186f/5/docker-entrypoint.sh#L21), [alpine](https://github.com/docker-library/elasticsearch/blob/d1765774a1effc5436f3d1f4ad6826dd9ed2186f/5/alpine/docker-entrypoint.sh#L21)).

**Comment by iemejia** [comment]
I partially agree with this one:
I think we should provide bash out of the box as you mention, that was the reason why we had in the previous version the default CMD ["sh", "-c"] as the last command so people could do docker run -it flink /bin/bash and have the same experience.

Where I don't agree is to remove the flink user, the two images you mention are core images and require root access to build from them, the flink application is installed in user land and ideally should be contained for security reasons.

**Comment by patricklucas** [comment]
I'm not suggesting remove the flink user, I'm suggesting remove the line `USER flink`, which causes all subsequent commands to be run as the flink user, including `bash`.

The official image docs suggest having `docker-entrypoint.sh` end with `exec "$@"` which makes `docker run ... bash` work, so we don't need that `CMD`. It already works now without it.

**Comment by patricklucas** [comment]
This issue is to drop privs in `docker-entrypoint.sh` to the flink user so that Flink runs as `flink`, but other commands run by a user are executed as `root`.

**Comment by iemejia** [comment]
ok, makes sense now. :+1:
