### ISSUE TITLE
New Images not recognizing jobmanager RPC

### ISSUE THREAD

**Issue by carterdanko** [docker-flink/docker-flink#50]
While using an older sha docker image `sha256:8757a61bd995dc43ba63d04ef575251fb36fc4e9794a3e9809fe7f443222ded8` the `JOB_MANAGER_RPC_ADDRESS` environment variable and configuration in the yaml file `jobmanager.rpc.address` are both recognized and used when the jobmanager/taskmanager starts up. 

In the latest docker images pushed up a few days ago, the rpc address is `cluster` and not being changed by the values being passed in.

**Comment by tillrohrmann** [comment]
Hi @carterdanko, this issue is caused by https://issues.apache.org/jira/browse/FLINK-8696 and should be fixed with https://github.com/docker-flink/docker-flink/pull/49. I think the updated docker files have not been pushed yet to docker hub. Could you verify this by building the images yourself?

**Comment by iemejia** [comment]
Oups I think this was my mistake, somehow I thought I had already pushed the updated images to the official-images repo. It should be ready some hours after they merge the PR, for ref
https://github.com/docker-library/official-images/pull/4911
Please confirm if ok @carterdanko

**Comment by carterdanko** [comment]
Ahh yeah that makes sense, after building the images myself it worked. Many thanks!
