### ISSUE TITLE
exec: local: not found

### ISSUE THREAD

**Issue by qinzhixing** [docker-flink/docker-flink#52]
When I run 
`docker run --name flink_local -p 8081:8081 -t flink local` 
It returns 
`/docker-entrypoint.sh: 58: exec: local: not found`

When I run
`docker ps -a`
It returns 
`CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                       PORTS               NAMES`
`4134e327eb89        flink               "/docker-entrypoin..."   2 minutes ago       Exited (127) 2 minutes ago                       flink_local
`

How can I start it?

**Comment by patricklucas** [comment]
Since Flink 1.5, Flink no longer supports a single integrated local mode. (See #49)

#44 was opened to explore ways to resurrect this functionality.
