### ISSUE TITLE
Docker's Official Images build of Flink is broken

### ISSUE THREAD

**Issue by lag-linaro** [docker-flink/docker-flink#59]
See the [Full Build Log](https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/flink/25/console) for details.

Snippet:
```
gpg: key 1F302569A96CFFD5: public key "Till Rohrmann (stsffap) <trohrmann@apache.org>" imported
gpg: Total number processed: 15
gpg:               imported: 15
gpg: no ultimately trusted keys found
+ gpg --batch --verify flink.tgz.asc flink.tgz
gpg: Signature made Wed Oct 17 20:23:15 2018 UTC
gpg:                using RSA key C2EED7B111D464BA
gpg: Good signature from "Chesnay Schepler (CODE SIGNING KEY) <chesnay@apache.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 19F2 195E 1B48 16D7 65A2  C324 C2EE D7B1 11D4 64BA
+ rm -rf /tmp/tmp.BgHhiG flink.tgz.asc
rm: can't remove '/tmp/tmp.BgHhiG/S.gpg-agent.ssh': No such file or directory
Removing intermediate container dab02cab8ec8
```

Essentially I think we're hitting [THIS BUG](https://stackoverflow.com/questions/45856100/remove-gnupghome-error-during-dockerfile-build).

@tianon @yosifkit any ideas from your side?

**Comment by patricklucas** [comment]
Thanks for the report. I've seen this a few times but never got around to tracking it down, since the build usually eventually completed and this seemed to occur no more often than [this](https://github.com/tianon/gosu/issues/35) issue.

I think I can solve them both—by iterating the list of keyservers and by using `gpgconf --kill all` respectively.

**Comment by patricklucas** [comment]
Thanks @tianon, will do that in #61. I think I'll still loop through the keyservers since I hit that issue extremely frequently when working on these builds locally.

**Comment by lag-linaro** [comment]
Please could you keep this open until the build succeeds:

https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/flink/

**Comment by patricklucas** [comment]
https://github.com/docker-library/official-images/pull/5035

**Comment by patricklucas** [comment]
@lag-linaro everything look good on your end? Feel free to close if so.

**Comment by lag-linaro** [comment]
Wonderful.  Thank you.
