### ISSUE TITLE
The docker image should not run as root

### ISSUE THREAD

**Issue by ndeslandes** [docker-flink/docker-flink#66]
A user flink (9999) is created but the docker image is still starting using root.
it is a security concern and it make it not usable in a kubernetes environment where the use of securityContext is enforced

When I start the image with user 999, I got a ```error: failed switching to "flink": operation not permitted```

here is an example fo the k8s manifest
```apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: flink:1.7.1-scala_2.11
          securityContext:
            runAsUser: 9999
            runAsNonRoot: true
          args:
            - taskmanager
          ports:
            - containerPort: 6121
              name: data
            - containerPort: 6122
              name: rpc
            - containerPort: 6125
              name: query
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: flink-jobmanager``

**Comment by patricklucas** [comment]
Thanks for the report @ndeslandes. I thought this image supported running as non-root from the beginning, but the unconditional use of gosu/su-exec means it will always fail to start as non-root, even if started as UID 9999 (the `flink` user).

A fix does seem straightforward, simply not invoking gosu/su-exec if the effective UID is 0.

**Comment by ndeslandes** [comment]
@patricklucas thanks, do you want me to make a PR?

**Comment by patricklucas** [comment]
@ndeslandes I'm working on it now, along with an additional test for running as non-root. I'll add you as a reviewer.

**Comment by iemejia** [comment]
Good catch @ndeslandes thanks for the awareness.
