### ISSUE TITLE
Run "non-root" test as flink user, not arbitrary user

### ISSUE THREAD

**Issue by patricklucas** [docker-flink/docker-flink#75]
It would be nice to run this test as an arbitrary user, but since we rely on writing out a config file, the image actually has to be run as either root or the `flink` user.

**Comment by diman82** [comment]
Isn't it possible to run as [Arbitrary User IDs](https://docs.openshift.com/enterprise/3.2/creating_images/guidelines.html#use-uid)?

I'm getting Permission denied errors in Openshift..

**Comment by patricklucas** [comment]
@diman82 it's tricky because this image needs to actually write out some config from `docker-entrypoint.sh` to work right, and therefore needs to run as `root` or `flink`.

However, the typical pattern for use in K8s is to skip this by generating a ConfigMap and overriding the default command.

It should include a `flink-conf.yaml` with the necessary values (e.g. `jobmanager.rpc.address`, `taskmanager.numberOfTaskSlots` etc.) and either set `FLINK_CONF_DIR` accordingly or mount the ConfigMap at `/opt/flink/conf`. (You'll want to include a log4j config in that case)

Finally, the "args" you use in your Pod template should be `["jobmanager.sh", "start-foreground"]` so that the usual entrypoint script is circumvented.

**Comment by diman82** [comment]
@patricklucas Yeah, that what I suspected.
Do you have a sample ConfigMap object by chance?

**Comment by patricklucas** [comment]
Might be a little out of date, but still illustrative: https://github.com/docker-flink/examples/blob/master/helm/flink/templates/configmap-flink.yaml

Also: https://ci.apache.org/projects/flink/flink-docs-master/ops/deployment/kubernetes.html#session-cluster-resource-definitions

**Comment by diman82** [comment]
@patricklucas Thanks for the reference.
Just to make sure - do I need to substitute the variables, i. e. {{ template "fullname" . }} or its being injected in the runtime? 
Specifically I'm referencing to:

    jobmanager.rpc.address: {{ template "fullname" . }}-jobmanager

**Comment by patricklucas** [comment]
Those would be filled in by helm at install time, so you need to put them yourself into the ConfigMap.

Per the linked docs, the basic structure is having 1 jobmanager pod (from a StatefulSet or Deployment or Job, depending) and a Deployment of taskmanagers, a Service to address the jobmanager by, and a ConfigMap that is mounted into all Pods. The ConfigMap's `flink-conf.yaml` key should have `jobmanager.rpc.address` set to the name of the Service.
