### ISSUE TITLE
Remove alpine image

### ISSUE THREAD

**Issue by iemejia** [docker-flink/docker-flink#79]
It seems that after https://github.com/docker-library/openjdk/pull/322 the official openjdk image (the one we are based on) won't support alpine anymore.
As analternative we may consider basing the alpine version on https://hub.docker.com/r/adoptopenjdk/openjdk11 but probably we'll do better to stay aligned with upstream.

**Comment by iemejia** [comment]
Notice that other architectures were removed too since they do not have upstream support. I don't remember our current status on this, but I think we are generating ours from the available ones so this should be 'automatic'. Can you confirm @patricklucas ?

**Comment by patricklucas** [comment]
Yeah, when we re-run `generate-stackbrew-library.sh` they should sync up. In fact, running it now it already complains about the missing alpine images upstream, so I will go ahead with this,
