### ISSUE TITLE
Drop 1.1 support after Flink 1.2.1 is released

### ISSUE THREAD

**Issue by patricklucas** [docker-flink/docker-flink#8]
I've included 1.1 in this repo since the start mainly to ensure the tooling in here works for multiple, concurrent supported releases, but I'm not sure it can actually be used from Docker effectively.

[FLINK-2821](https://issues.apache.org/jira/browse/FLINK-2821) found that the hostname of the jobmanager has to be exactly the same as the name the taskmanagers connect to it with, due to Akka. A fix/workaround for this was added in 1.2, but as far as I know it wasn't backported to 1.1.

We should actually try out the 1.1 images to see if they work at all, and if not, just drop support and provide official images for 1.2 onward.

Edit: original title "Evaluate and possibly delete 1.1 support" changed to "Drop 1.1 support after Flink 1.2.1 is released"

**Comment by patricklucas** [comment]
So, I'm a bit confused, because a cursory test suggests 1.1 actually works fine in Docker.

I used the `docker-compose.yml` file from flink/master and used a 1.1 image built from this repo, and the cluster came up with all task managers present and able to accept jobs.

It doesn't look like the changes from FLINK-2821 are in 1.1.4, so I'm not really sure why this works... maybe @jgrier or @StephanEwen have some idea?

**Comment by patricklucas** [comment]
Hmm possibly the case that didn't work was HA mode. I've skimmed through all the comments on FLINK-2821 and there appear to be quite a few facets of the overall issue, but the simple case I demonstrated here might be one that actually works: Flink appears to resolve 'jobmanager' to the actual IP at runtime, so the akka URL just has the internal IP which works on the same host, but maybe not across hosts?

**Comment by StephanEwen** [comment]
@patricklucas I think your latest comment has the answer. In Flink 1.1 Akka could bind only to the internal IP which would not work across hosts.

**Comment by StephanEwen** [comment]
+1 to drop 1.1 support after 1.2.1 is out (it has some crucial fixes).

**Comment by patricklucas** [comment]
Thanks @StephanEwen, I'll update this issue to that effect.

**Comment by iemejia** [comment]
@StephanEwen one question, is there any possibility of backporting the start-foreground shell scripts ? This will help us to have everything in place to have the best docker image possible from 1.2.1 and we won't have to maintain different docker-entrypoints for the Docker image.

**Comment by iemejia** [comment]
For ref.
https://issues.apache.org/jira/browse/FLINK-4326
https://github.com/apache/flink/pull/3492/files

**Comment by iemejia** [comment]
I just saw the vote started for 1.1.5, so I suppose 1.2.1 will come quite fast so maybe it won't make the cut the backport, well never mind, we will deal with it.

**Comment by StephanEwen** [comment]
@iemejia I have cherry picked the change back to the 1.2 branch, currently testing.
If it works well, we'll have it in the 1.2.1 release.

**Comment by iemejia** [comment]
Awesome, thanks @StephanEwen !

**Comment by StephanEwen** [comment]
@iemejia Merged into the 1.2 release branch

**Comment by imejia** [comment]
Great! No need for double docker entrypoint ! Thanks.
