### ISSUE TITLE
Should the debian- or alpine-based images be the default?

### ISSUE THREAD

**Issue by patricklucas** [docker-flink/docker-flink#9]
Most projects appear to make their default (e.g. "latest" "1.2") images be those based on debian, but what's the real benefit there? The alpine images are significantly smaller, and I don't see why we shouldn't have them be the default, relegating the debian-based images to e.g. "latest-debian" and "1.2-debian".

**Comment by iemejia** [comment]
Yes, the default tends to be the debian one, I suppose the benefit is extensibility and sysdmin skills. There are tons of extra packages in debian that don't even exist in Alpine, and way more documentation on how to extend or hack extra stuff for debian derived 'distributions/images' so I suppose people prefer them for those reasons.

I think we should follow the default, even if I agree that the smallest versions make also sense. Anyway users can choose they image they prefer.

**Comment by patricklucas** [comment]
Yeah that makes sense.

Another thing is that other images that have an alpine use the tag 'alpine' in lieu of 'latest', rather than 'latest-alpine' like we have it now. For example, one project has "5 5.1 latest 5-alpine 5.1-alpine alpine" tags, whereas we would have "5 5.1 latest 5-alpine 5.1-alpine latest-alpine".

I think the was we're doing it now makes the most sense for us, given the other variants we have to support—it's more consistent to have the same set of tags with and without "-alpine" appended.
