### ISSUE TITLE
Add new image based on Java 11

### ISSUE THREAD

**Issue by nvilmer** [docker-flink/docker-flink#97]
Since 1.10.0 supports Java 11, please add image base on Java 11. Thanks.

**Comment by patricklucas** [comment]
I agree this would be a nice improvement, however this repo is now archived in favor of https://github.com/apache/flink-docker.

Could you open an issue on the [FLINK Jira project](https://issues.apache.org/jira/browse/FLINK) suggesting this?

**Comment by patricklucas** [comment]
We just created the component [Release System / Docker](https://issues.apache.org/jira/issues/?jql=project%20%3D%20FLINK%20AND%20component%20%3D%20%22Release%20System%20%2F%20Docker%22) that this issue can be created under.

**Comment by iemejia** [comment]
For ref, created the issue in Flink's JIRA, I have a PR ready for the images but still need to fix the tags generation.
https://issues.apache.org/jira/browse/FLINK-16260

**Comment by balint133** [comment]
@iemejia Hi, any update on your PR?

**Comment by nvilmer** [comment]
I ended up building my own image; I need to add the rsync daemon anyway.
-- Norm

"Music is so important in our lives" 

    On Tuesday, March 17, 2020, 08:06:05 PM CDT, Balint <notifications@github.com> wrote:  
 
 


@iemejia Hi, any update on your PR?

**Comment by iemejia** [comment]
Sorry for the delay, hard times with the whole coronavirus stuff. I finally got some time to work on this. The PR is now open in the new repo and hopefully it will be merged/released soon for ref:
https://github.com/apache/flink-docker/pull/9

**Comment by iemejia** [comment]
I am going to close this issue in favor of the regular FLINK issue please watch that one for more updates: https://issues.apache.org/jira/browse/FLINK-16260
